### PR TITLE
Remove search service

### PR DESCRIPTION
**Pull request by emmberk**
Additionally, this PR cleans up a lot of classes that weren't being used and combines the storeProduct and retrieveProduct Controllers to prepare for adding a dependency on https://github.com/connexta/ion-store-api.

Deployment should still work:
- `docker stack deploy -c docker-compose.yml store-stack`
- `./deployments/local-minio/deploy.sh`
- `./gradlew deploy`

### CODE REVIEW

**Comment by emmberk** [comment]
`./gradlew clean build` and `./gradlew dependencyCheckAnalyze --info` succeed for me

**Comment by emmberk** [comment]
Overriding the check for 2 approvers because Josh is out and we are not about to release

**Comment by emmberk** [comment]
This is blocked by an issue storing products in S3:
```AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method```

**Comment by ahoffer** [comment]
I have heroed this PR.

**Pull request merged**
